### ISSUE TITLE
explaining MASTER

### ISSUE THREAD

**Issue by russmaxdesign** [charleso/git-training#2]
On this page

https://github.com/charleso/git-training/blob/master/head.md

There is a step by step process taking users down to the HEAD, but MASTER is not clearly explained on the way. 

> **master** is the name of the default branch that git creates for you when first creating a repo. In most cases, "master" means "the main branch".

Or something...

**Comment by charleso** [comment]
@russmaxdesign I've add a few tweaks regarding head/master [here](https://github.com/charleso/git-training/commit/5b189b68e6a0148c2057c9032f4a2488794ce70b). Not sure if that helps or not.
