### ISSUE TITLE
Clone

### ISSUE THREAD

**Issue by Ruegen** [charleso/git-training#6]
In clone 

cd test-clone

> git --graph --oneline --decorate master

errors here for me

https://github.com/charleso/git-training/blob/master/remotes.md

dropping master worked for me though..

**Comment by Ruegen** [comment]
also 

```
> ls -F .git/refs/remotes/origin

master
```

returned 

`hello master`

I got two returned instead of one...

**Comment by charleso** [comment]
Whoops, previously had been cloning a different repo with only one branch. Good catch, thanks.
