### ISSUE TITLE
push.md

### ISSUE THREAD

**Issue by Ruegen** [charleso/git-training#7]
in the "So where were we?" section this didn't work for me

```
> git --graph --oneline --decorate my_master

* 41ce7fa (HEAD, origin/master, my_master) Third commit
* 672e562 Second commit
* 406bb3b Initial commit
```

however adding log did work

`So where were we?

> git log --graph --oneline --decorate my_master
- 41ce7fa (HEAD, origin/master, my_master) Third commit
- 672e562 Second commit
- 406bb3b Initial commit`

the next part is also missing log I think

**Comment by charleso** [comment]
Yep, quite a few copy+pasta errors. Fixed, thanks!
