### ISSUE TITLE
Change 'not' to 'nothing' -- second sentence on Git-Remote Clone page

### ISSUE THREAD

**Issue by alexi21** [charleso/git-training#8]
Normally you'll find yourself cloning something from the web, and in particular Github. However, there's not special about Github, and in fact for the purposes of this guide let's clone the repository we've just been working in.

**Comment by charleso** [comment]
Thanks @alexi21 https://github.com/charleso/git-training/commit/e1f197b22631cf65ec4e74bb6b5532c375af5380
